###
GET http://localhost:3000/users


###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Tom",
    "email": "tom@mail.com"
}


###
GET http://localhost:3000/users/2


###
PUT  http://localhost:3000/users/2
Content-Type: application/json

{
    "email": "tom2@mail.com"
}



###
DELETE http://localhost:3000/users/2