###
GET http://localhost:3000/products


###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product #1",
    "price": 200
}


###
GET http://localhost:3000/products/1


###
PUT  http://localhost:3000/products/1
Content-Type: application/json

{
    "name": "Product #1",
    "price": 300
}



###
DELETE http://localhost:3000/products/1